# Utilisez une image légère et compatible
FROM node:16-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY package.json ./
COPY package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers
COPY . .

# Construire l'application pour la production
RUN npm run build

# Exposer le port pour le serveur
EXPOSE 3000

# Commande par défaut pour exécuter l'application
CMD ["npm", "start"]
