FROM node:18.20.5

WORKDIR /app

# Copy package files
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy all files in the server directory
COPY ./ . 

EXPOSE 4000

CMD ["node", "--max-old-space-size=4096", "server.js"]
