FROM node:18.20.5

# Installation des dépendances de compilation
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY server/package*.json ./
RUN npm install

COPY server/ .

EXPOSE 4000

CMD ["node", "--max-old-space-size=4096", "server.js"]