name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Docker Services
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construction de l'image frontend
      - name: Build Docker image pour le frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f Dockerfile.frontend .

      # Étape 4 : Construction de l'image backend
      - name: Build Docker image pour le backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f server/Dockerfile.backend .

      # Étape 5 : Push des images Docker sur Docker Hub
      - name: Push Docker images à Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Étape 6 : Déploiement des services avec Docker Compose
      - name: Deploy services avec Docker Compose
        run: |
          docker compose down || true
          docker compose pull
          docker compose up -d
