name: CI/CD Pipeline

on:
  push:
    branches:
      
main  
pull_request:
  branches:
main  

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      
      
name: Checkout repository
      uses: actions/checkout@v3

      # 2. Se connecter à Docker Hub
      
name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construire les images Docker
      
name: Build frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f Dockerfile.frontend .

      
name: Build backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f ./server/Dockerfile.backend ./server

      # 4. Lancer les conteneurs avec Docker Compose
      
name: Start services with Docker Compose
      run: |
        docker-compose up -d

      
name: Stop Docker containers
      run: docker-compose down