name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Docker Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image pour le frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f Dockerfile.frontend .

      - name: Build Docker image pour le backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f ./server/Dockerfile.backend ./server

      - name: Push Docker images a Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Deploy services avec Docker Compose
        run: |
          docker compose down
          docker compose pull
          docker compose up -d